# Generated by Django 5.0 on 2023-12-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects_images')),
                ('title', models.CharField(choices=[('DC', 'Duct Cleaning'), ('FI', 'Furnace Installation'), ('FR', 'Furnace Repair'), ('FC', 'Furnace Cleaning'), ('AI', 'Air Conditioner Installation'), ('AR', 'Air Conditioner Tune Up')], max_length=2)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
