# Generated by Django 5.0 on 2023-12-26 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('DI', 'Free Duct Inspection'), ('FS', 'Free Sanitization'), ('DC', 'Duct Cleaning'), ('FI', 'Furnace Installation'), ('FR', 'Furnace Repair'), ('FC', 'Furnace Cleaning'), ('AI', 'Air Conditioner Installation'), ('AR', 'Air Conditioner Tune Up')], max_length=2)),
                ('is_user', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('order_time', models.DateTimeField(auto_now=True)),
                ('finished_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
