# Generated by Django 5.0 on 2023-12-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='created_at')),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers_images')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_till', models.DateTimeField(blank=True, null=True)),
                ('availability', models.CharField(choices=[('A', 'Available'), ('E', 'Expired')], default='A', max_length=1)),
            ],
        ),
    ]
